FROM node:8

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org && cnpm install -g pm2 && mkdir -p /usr/src/app

COPY ./code /usr/src/app

WORKDIR /usr/src/app

RUN npm install
RUN npm i node-sass -D

ENV HOST 0.0.0.0

EXPOSE 9527
CMD ["npm","run","dev"]
